(()=>{
  'use strict';
  const MORPHEME_TARGETS=[
    {id:'plural-s',label:'-s',kind:'suffix',meaning:'more than one',words:['books','digits','nights','shapes']},
    {id:'plural-es',label:'-es',kind:'suffix',meaning:'more than one',words:['matches','benches','dishes','boxes']},
    {id:'past-ed',label:'-ed',kind:'suffix',meaning:'happened in the past',words:['crawled','reached','visited','played','picked','rested','walked','replayed','disliked']},
    {id:'prefix-un',label:'un-',kind:'prefix',meaning:'not / opposite of',words:['unscrew','unhappy','unlucky','unable']},
    {id:'prefix-in',label:'in-',kind:'prefix',meaning:'not',words:['incomplete','incorrect','insane']},
    {id:'suffix-ing',label:'-ing',kind:'suffix',meaning:'action happening now / continuing',words:['singing','drawing','feeling','disobeying']},
    {id:'suffix-ful',label:'-ful',kind:'suffix',meaning:'full of / having',words:['stressful','powerful','thankful']},
    {id:'prefix-re',label:'re-',kind:'prefix',meaning:'again',words:['rethink','reread','redo','replayed','reuse']},
    {id:'prefix-dis',label:'dis-',kind:'prefix',meaning:'not / opposite / apart',words:['disbelief','disobeying','disliked']},
    {id:'comparative-er',label:'-er',kind:'suffix',meaning:'more (comparing two)',words:['brighter','greater','longer']},
    {id:'superlative-est',label:'-est',kind:'suffix',meaning:'most (comparing three or more)',words:['brightest','greatest','longest']},
    {id:'prefix-mis',label:'mis-',kind:'prefix',meaning:'wrongly / badly',words:['misuse','mistrust','mislead','misbehave','misplace','miscount']},
    {id:'prefix-pre',label:'pre-',kind:'prefix',meaning:'before',words:['pretest','preview','prepaid','preheat','precook','premix']},
    {id:'suffix-less',label:'-less',kind:'suffix',meaning:'without',words:['restless','harmless','homeless','helpless','hopeless','endless','useless']}
  ];
  const WORD_TO_MORPHEMES=new Map();
  MORPHEME_TARGETS.forEach(m=>m.words.forEach(word=>{const key=String(word).toLowerCase();if(!WORD_TO_MORPHEMES.has(key))WORD_TO_MORPHEMES.set(key,[]);WORD_TO_MORPHEMES.get(key).push(m);}));
  const morphsInWord=w=>WORD_TO_MORPHEMES.get(String(w?.word||w||'').toLowerCase())||[];
  function globalUsedWords(){if(typeof state==='undefined'||!state.players)return new Set();return new Set(state.players.flatMap(p=>[...p.usedWords].map(x=>String(x).toLowerCase())))}
  function presentedMorphology(){const used=globalUsedWords(),covered=new Set();if(typeof state==='undefined'||!state.words)return covered;state.words.forEach(w=>{if(used.has(String(w.word).toLowerCase()))morphsInWord(w).forEach(m=>covered.add(m.id));});return covered}
  function presentedPhonograms(){const used=globalUsedWords(),covered=new Set();if(typeof state==='undefined'||!state.words)return covered;state.words.forEach(w=>{if(used.has(String(w.word).toLowerCase()))wordTokenKeys(w).forEach(k=>covered.add(k));});return covered}
  function remainingSets(){const phonCovered=presentedPhonograms(),morphCovered=presentedMorphology();return{phon:new Set(state.allTokens.map(tokenKey).filter(k=>!phonCovered.has(k))),morph:new Set(MORPHEME_TARGETS.map(m=>m.id).filter(id=>!morphCovered.has(id)))}}
  function morphologyFreshCount(w,remainingMorph){return morphsInWord(w).filter(m=>remainingMorph.has(m.id)).length}
  function syllablesIn(w){return Math.max(1,Array.isArray(w?.syllables)?w.syllables.length:1)}
  function tilesIn(w){return(w?.syllables||[]).reduce((n,s)=>n+(s.letters||[]).length,0)}
  function scoreCandidate(w,remainingPhon,remainingMorph,randomness=10){const phonFresh=wordTokenKeys(w).filter(k=>remainingPhon.has(k)).length,morphFresh=morphologyFreshCount(w,remainingMorph);return{w,phonFresh,morphFresh,score:morphFresh*12000+phonFresh*10000-syllablesIn(w)*6-tilesIn(w)*.35+Math.random()*randomness}}
  function pickCoverageWord(candidates,remainingPhon,remainingMorph,randomness=10){if(!candidates.length)return null;const scored=candidates.map(w=>scoreCandidate(w,remainingPhon,remainingMorph,randomness)).sort((a,b)=>b.score-a.score);const bestCoverage=(scored[0]?.morphFresh||0)*100+(scored[0]?.phonFresh||0);const peers=scored.filter(x=>x.morphFresh*100+x.phonFresh===bestCoverage).slice(0,8),pool=peers.length?peers:scored.slice(0,6);return pool[Math.floor(Math.random()*pool.length)]?.w||scored[0].w}
  if(typeof chooseCoverageWord==='function'){chooseCoverageWord=function(){if(typeof randomMissionQueue!=='undefined'&&randomMissionQueue.length){const queued=randomMissionQueue.shift();if(queued)return queued}const used=globalUsedWords(),unused=state.words.filter(w=>!used.has(String(w.word).toLowerCase()));if(!unused.length)return null;const remaining=remainingSets(),useful=unused.filter(w=>wordTokenKeys(w).some(k=>remaining.phon.has(k))||morphsInWord(w).some(m=>remaining.morph.has(m.id)));return pickCoverageWord(useful.length?useful:unused,remaining.phon,remaining.morph,12)}}
  if(typeof buildRandomMissionQueue==='function'){buildRandomMissionQueue=function(){const used=globalUsedWords(),remaining=remainingSets();let available=state.words.filter(w=>{const key=String(w.word||'').toLowerCase();return!used.has(key)&&(typeof randomMissionRerollExclusions==='undefined'||!randomMissionRerollExclusions.has(key))});const queue=[];for(let slot=0;slot<10&&available.length;slot++){const useful=available.filter(w=>wordTokenKeys(w).some(k=>remaining.phon.has(k))||morphsInWord(w).some(m=>remaining.morph.has(m.id))),pick=pickCoverageWord(useful.length?useful:available,remaining.phon,remaining.morph,45);if(!pick)break;queue.push(pick);available=available.filter(w=>w!==pick);wordTokenKeys(pick).forEach(k=>remaining.phon.delete(k));morphsInWord(pick).forEach(m=>remaining.morph.delete(m.id))}return queue}}
  function ensureMorphUI(){let chip=document.getElementById('morphCoverageChip');const strip=document.querySelector('.missionStrip');if(!chip&&strip){chip=document.createElement('span');chip.id='morphCoverageChip';chip.className='missionChip morphCoverageChip';chip.title='Morphology and morpheme coverage';strip.appendChild(chip)}const legend=document.querySelector('.legend');if(legend&&!document.getElementById('morphLegend')){const item=document.createElement('span');item.id='morphLegend';item.className='legendChip';item.textContent='🧩 Morpheme = meaningful word part';legend.appendChild(item)}const teacher=document.getElementById('coverageTokenList');if(teacher&&!document.getElementById('morphTeacherList')){const box=document.createElement('div');box.id='morphTeacherList';box.className='morphTeacherList';teacher.insertAdjacentElement('afterend',box)}return chip}
  function updateMorphUI(){const chip=ensureMorphUI(),covered=presentedMorphology();if(chip){chip.textContent=`🧩 Morphemes ${covered.size}/${MORPHEME_TARGETS.length}`;chip.classList.toggle('morphComplete',covered.size===MORPHEME_TARGETS.length)}const teacher=document.getElementById('morphTeacherList');if(teacher){teacher.innerHTML='<b>Morphology target ('+MORPHEME_TARGETS.length+'):</b> '+MORPHEME_TARGETS.map(m=>`<span class="morphTeacherItem ${covered.has(m.id)?'done':''}">${covered.has(m.id)?'✓ ':'○ '}${m.label} <small>${m.meaning}</small></span>`).join(' ')}}
  function explainCurrentMorphology(){if(typeof state==='undefined'||!state.current)return;const ms=morphsInWord(state.current);if(!ms.length)return;const msg=ms.map(m=>`${m.label} = ${m.meaning}`).join(' • '),feedbackEl=document.getElementById('feedback');if(feedbackEl&&state.solved){const base=feedbackEl.textContent.trim();if(!base.includes('🧩'))feedbackEl.textContent=base+'  🧩 '+msg}const chip=document.getElementById('morphCoverageChip');if(chip){chip.title=msg;chip.dataset.lastMorph=msg}}
  if(typeof checkAnswer==='function'){const originalCheck=checkAnswer;checkAnswer=function(){const wasSolved=!!state.solved;originalCheck.apply(this,arguments);updateMorphUI();if(!wasSolved&&state.solved)explainCurrentMorphology()}}
  if(typeof updateStats==='function'){const originalUpdateStats=updateStats;updateStats=function(){const result=originalUpdateStats.apply(this,arguments);updateMorphUI();return result}}
  const style=document.createElement('style');style.id='morphology-style';style.textContent='.morphCoverageChip{background:#f4ecff!important;border-color:#c9b0ee!important;color:#604494!important}.morphCoverageChip.morphComplete{background:#e8f7ec!important;border-color:#98d7ad!important;color:#247248!important}.morphTeacherList{margin-top:10px;padding:9px;border:1.5px solid #d9c9ee;border-radius:12px;background:#faf7ff;font-size:12px;line-height:1.55;color:#53697a}.morphTeacherItem{display:inline-block;margin:2px 3px;padding:3px 6px;border-radius:8px;background:#f0edf4}.morphTeacherItem.done{background:#e7f7ec;color:#27754b}.morphTeacherItem small{font-size:10px;font-weight:700}@media(max-width:620px){.morphCoverageChip{font-size:8.5px!important;padding:2px 5px!important}.morphTeacherList{font-size:10px}}';document.head.appendChild(style);
  const rules=document.querySelector('#startScreen .rulesBox');if(rules){rules.innerHTML=rules.innerHTML.replace('The 60-word set covers every taught phonogram at least once.','The 60-word set covers every taught phonogram <b>and every taught morphology/morpheme target</b> at least once.')}
  updateMorphUI();
})();